# Generated by Django 2.1.2 on 2018-12-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitp_connect', '0004_auto_20181130_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_logo', models.FileField(default='', upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.CharField(max_length=800),
        ),
    ]
