# Generated by Django 2.1.2 on 2018-12-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iitp_connect', '0007_userlogo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogo',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserLogo',
        ),
    ]
