# Generated by Django 2.1.2 on 2018-12-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitp_connect', '0008_auto_20181201_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_tag',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found'), ('Buy', 'Buy'), ('Sell', 'Sell'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
