# Generated by Django 2.1.2 on 2018-12-01 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iitp_connect', '0009_auto_20181201_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_logo',
            new_name='item_pic',
        ),
    ]
