# Generated by Django 2.1.2 on 2018-12-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitp_connect', '0010_auto_20181201_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.IntegerField(choices=[('1', 'Open'), ('0', 'Closed')], default='1', max_length=2),
        ),
    ]
