# Generated by Django 2.1.2 on 2018-12-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitp_connect', '0015_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='profile_pic',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
