# Generated by Django 2.1.2 on 2018-12-03 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitp_connect', '0016_auto_20181202_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_event', models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 3, 17, 43, 28, 377798))),
            ],
        ),
    ]
