# Generated by Django 2.1.2 on 2018-12-03 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitp_connect', '0017_cab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='date_of_event',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 3, 17, 58, 7, 246131)),
        ),
    ]
