# Generated by Django 2.1.2 on 2018-12-03 19:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iitp_connect', '0018_auto_20181203_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Danapur Station', 'Danapur Station'), ('Patna Station', 'Patna Station'), ('IIT Patna', 'IIT Patna'), ('Patna Airport', 'Patna Airport'), ('Boys Hostel', 'Boys Hostel'), ('Girls Hostel', 'Girls Hostel'), ('Other', 'Other')], default='Other', max_length=100)),
                ('destination', models.CharField(choices=[('Danapur Station', 'Danapur Station'), ('Patna Station', 'Patna Station'), ('IIT Patna', 'IIT Patna'), ('Patna Airport', 'Patna Airport'), ('Boys Hostel', 'Boys Hostel'), ('Girls Hostel', 'Girls Hostel'), ('Other', 'Other')], default='Other', max_length=100)),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 3, 19, 32, 53, 951794))),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cab',
            name='date_of_event',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 3, 19, 32, 53, 952179)),
        ),
    ]
