# Generated by Django 2.1.2 on 2018-12-03 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitp_connect', '0019_auto_20181203_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='date_of_event',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 3, 20, 2, 6, 283483)),
        ),
        migrations.AlterField(
            model_name='cabservice',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 3, 20, 2, 6, 283106)),
        ),
    ]
