# Generated by Django 2.1.2 on 2018-12-03 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitp_connect', '0020_auto_20181203_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabservice',
            name='book_status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Unbooked', 'Unbooked')], default='Unbooked', max_length=20),
        ),
        migrations.AlterField(
            model_name='cab',
            name='date_of_event',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 3, 20, 47, 59, 558054)),
        ),
        migrations.AlterField(
            model_name='cabservice',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 3, 20, 47, 59, 557632)),
        ),
    ]
