# Generated by Django 2.1.2 on 2018-12-03 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitp_connect', '0021_auto_20181203_2047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cab',
        ),
        migrations.AlterField(
            model_name='cabservice',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 3, 21, 30, 27, 545682)),
        ),
    ]
