# Generated by Django 2.1.2 on 2018-12-03 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitp_connect', '0022_auto_20181203_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_event', models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 3, 21, 34, 58, 846791))),
            ],
        ),
        migrations.AlterField(
            model_name='cabservice',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 3, 21, 34, 58, 846373)),
        ),
    ]
