# Generated by Django 2.1.2 on 2018-12-03 22:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iitp_connect', '0025_auto_20181203_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabservice',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 3, 22, 4, 49, 258653, tzinfo=utc)),
        ),
    ]
