# Generated by Django 2.1.2 on 2018-12-03 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iitp_connect', '0026_auto_20181203_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabservice',
            name='date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
